// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppInput: typeof import('./components/AppInput.vue')['default']
    BookNowDrawer: typeof import('./components/BookNowDrawer.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ComingSoon: typeof import('./components/ComingSoon.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    ContactBottomLeftIcon: typeof import('./components/ContactBottomLeftIcon.vue')['default']
    ContactBottomRightIcon: typeof import('./components/ContactBottomRightIcon.vue')['default']
    ContactInput: typeof import('./components/ContactInput.vue')['default']
    DesktopNavbar: typeof import('./components/Navbar/DesktopNavbar.vue')['default']
    ErrorMessage: typeof import('./components/ErrorMessage.vue')['default']
    FeatureItem: typeof import('./components/FeatureItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    MainIntro: typeof import('./components/MainIntro.vue')['default']
    MobileNavbar: typeof import('./components/Navbar/MobileNavbar.vue')['default']
    MobileNavDrawer: typeof import('./components/Navbar/MobileNavDrawer.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    Navbar2: typeof import('./components/Navbar2.vue')['default']
    NavbarLogo: typeof import('./components/NavbarLogo.vue')['default']
    Order: typeof import('./components/Order.vue')['default']
    PageSpinner: typeof import('./components/PageSpinner.vue')['default']
    README: typeof import('./components/README.md')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    SignatureItem: typeof import('./components/SignatureItem.vue')['default']
    SignWaiver: typeof import('./components/SignWaiver.vue')['default']
    Stripe: typeof import('./components/Stripe.vue')['default']
    SuccessfulOrder: typeof import('./components/SuccessfulOrder.vue')['default']
    TestimonialItem: typeof import('./components/TestimonialItem.vue')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    TwoFeatures: typeof import('./components/TwoFeatures.vue')['default']
    WhoWeAre: typeof import('./components/WhoWeAre.vue')['default']
  }
}

export { }
