// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    MainIntro: typeof import('./components/MainIntro.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PhoneIcon: typeof import('~icons/ph/one-icon')['default']
    README: typeof import('./components/README.md')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    TwoFeatures: typeof import('./components/TwoFeatures.vue')['default']
  }
}

export { }
